server:
  port: 8090
  servlet:
    # cookie 30 天过期
    session:
      cookie:
        max-age: 2592000
        #cookie作用域
        domain: #
spring:
  application:
    name: api-gateway
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
    gateway:
      routes:
        - id: api_route
          uri: lb://api-backend
          predicates:
            - Path=/api/**
  redis:
    database: 1
    host: localhost
    port: 6379
    timeout: 5000
    password: #

logging:
  level:
    org:
      springframework:
        cloud:
          gateway:
            trace

dubbo:
  application:
    name: dubbo
    qosEnableL: true
    qosPort: 33333
    qosAcceptForeignIp: false
  protocol:
    name: dubbo
    port: -1
  registry:
    address: nacos://localhost:8848
